apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    app: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: hamnairfan96/result-app:latest
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: PG_HOST
              value: postgres-service
            - name: PG_PORT
              value: "5432"
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  selector:
    app: result
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
